export const PROJECTS = [
    // ─── Full Stack ───────────────────────────────────────────────
    {
        id: 'ironcore-gym', title: 'Ironcore Gym', category: 'Full Stack',
        tagline: 'Gym Management Platform',
        description: 'A full-stack gym management platform with amenities, membership plans, trainer profiles, a BMI calculator, AI-based personalized diet plans, and a fitness blog.',
        features: ['Membership plans & trainer profiles', 'AI-based personalized diet plans', 'BMI Calculator with health insights', 'JWT authentication & protected routes', 'Fitness blogs & wellness section', 'Postman-documented REST API'],
        technologies: ['React.js', 'Node.js', 'MongoDB', 'Express.js', 'JWT', 'Postman'],
        images: [
            'https://res.cloudinary.com/dlqyrgblr/image/upload/v1739895481/uagv0dunqcqtqmmsqs6z.png',
            'https://res.cloudinary.com/dlqyrgblr/image/upload/v1771775370/Ironcore_2_xxnucf.png',
            'https://res.cloudinary.com/dlqyrgblr/image/upload/v1771775377/Ironcore_3_gztkfl.png',
            'https://res.cloudinary.com/dlqyrgblr/image/upload/v1771775369/Ironcore_4_nb34gs.png',
            'https://res.cloudinary.com/dlqyrgblr/image/upload/v1771775371/Ironcore_5_xg6rcy.png',
            'https://res.cloudinary.com/dlqyrgblr/image/upload/v1771775372/Ironcore_6_usjyts.png',
        ],
        links: [
            { label: 'GitHub', url: 'https://github.com/Ridham2808/ironcore_gym', type: 'github' },
            { label: 'Live Site', url: 'https://ironcore-gym-2.onrender.com', type: 'live' },
            { label: 'Demo Video', url: 'https://www.youtube.com/watch?v=PhFP8Qhr9jc', type: 'video' },
            { label: 'API Docs', url: 'https://documenter.getpostman.com/view/39189278/2sAYX3rPFi', type: 'docs' },
            { label: 'Closed PRs', url: 'https://github.com/codinggita/ironcore_gym/pulls?q=is%3Apr+is%3Aclosed', type: 'pr' },
        ],
    },
    {
        id: 'data-explorer', title: 'React Data Explorer', category: 'Full Stack',
        tagline: 'Multi-API Data Platform',
        description: 'A React-based data exploration platform that fetches and displays multiple datasets including meals, cocktails, Harry Potter, albums, sports teams, and banking data via real-time APIs.',
        features: ['6+ real-time API integrations', 'Dynamic search & filtering', 'Smooth UI transitions', 'Responsive card layouts', 'Category-based dataset switching'],
        technologies: ['React.js', 'Node.js', 'Express.js', 'REST APIs', 'CSS3'],
        images: [
            'https://res.cloudinary.com/dlqyrgblr/image/upload/v1739895464/fuda1jdna7g1acnzmpfc.png',
            'https://res.cloudinary.com/dlqyrgblr/image/upload/v1771775645/Data_2_ofzuyo.png',
            'https://res.cloudinary.com/dlqyrgblr/image/upload/v1771775642/Data_3_fftcur.png',
            'https://res.cloudinary.com/dlqyrgblr/image/upload/v1771775644/Data_4_jlhd4l.png',
            'https://res.cloudinary.com/dlqyrgblr/image/upload/v1771775637/Data_5_zvrxge.png',
        ],
        links: [
            { label: 'GitHub', url: 'https://github.com/Ridham2808/Data_explorer', type: 'github' },
            { label: 'Live Site', url: 'https://data-explorer-kn6w.onrender.com/', type: 'live' },
            { label: 'Demo Video', url: 'https://www.youtube.com/watch?v=Iek5FGbtn', type: 'video' },
        ],
    },
    {
        id: 'youtube-clone', title: 'YouTube Clone', category: 'Full Stack',
        tagline: 'Video Platform Clone',
        description: 'A YouTube-inspired platform with search, video filtering by categories, playback with suggestions and sidebar navigation — built with MERN stack.',
        features: ['Category-based video filtering', 'Real-time search', 'Video playback with suggestions', 'Responsive sidebar navigation', 'MongoDB-powered backend'],
        technologies: ['React.js', 'Node.js', 'MongoDB', 'Express.js', 'CSS3'],
        images: ['https://res.cloudinary.com/dlqyrgblr/image/upload/v1739895518/ifo9rhikhmexnxz2ygdv.png'],
        links: [
            { label: 'GitHub', url: 'https://github.com/Ridham2808/Youtube-React', type: 'github' },
            { label: 'Live Site', url: 'https://youtube-react-5nna.onrender.com', type: 'live' },
        ],
    },
    {
        id: 'bamoka', title: 'Bamoka Industries Clone', category: 'Full Stack',
        tagline: 'Industrial UI Clone',
        description: 'A Bamoka Industries UI clone in React with professional industrial layout, product showcase sections, and fully responsive design.',
        features: ['Professional industrial layout', 'Product showcase sections', 'Responsive design', 'Smooth hover transitions'],
        technologies: ['React.js', 'CSS3', 'Responsive Design'],
        images: ['https://res.cloudinary.com/dlqyrgblr/image/upload/v1739895450/tjsn0k7o7odxseqbsu7a.png'],
        links: [
            { label: 'GitHub', url: 'https://github.com/Ridham2808/Bamoka-Industries-React', type: 'github' },
            { label: 'Live Site', url: 'https://bamoka-industries-react.netlify.app/', type: 'live' },
        ],
    },
    {
        id: 'spotify-react', title: 'Spotify Clone (React)', category: 'Full Stack',
        tagline: 'Music Platform UI',
        description: 'A Spotify UI clone with dark-themed design, playlist sections, and responsive music player layout built in React.',
        features: ['Dark theme design system', 'Playlist & album sections', 'Responsive music player', 'Smooth UI animations'],
        technologies: ['React.js', 'Node.js', 'CSS3'],
        images: ['https://res.cloudinary.com/dlqyrgblr/image/upload/v1739895496/yriynva7qupk6gnhfcmj.png'],
        links: [
            { label: 'GitHub', url: 'https://github.com/Ridham2808/Spotify-React', type: 'github' },
        ],
    },

    // ─── Hackathon ────────────────────────────────────────────────
    {
        id: 'climapredict', title: 'ClimaPredict', category: 'Hackathon',
        tagline: 'AI for Rural Resilience · Indradhanu 2026',
        description: 'An AI-powered weather intelligence platform built for rural farmers — predicts climate patterns to help communities make smarter agricultural and livestock decisions.',
        features: ['AI-based crop weather prediction', 'Regional climate pattern analysis', 'Risk assessment dashboard', 'Multi-language support for rural users', 'Real-time weather data integration'],
        technologies: ['React.js', 'Python', 'AI/ML', 'Weather API', 'REST APIs'],
        images: [
            'https://res.cloudinary.com/dlqyrgblr/image/upload/v1771770011/Clima_1_tenc1q.jpg',
            'https://res.cloudinary.com/dlqyrgblr/image/upload/v1771770011/Clima_2_jvpri6.jpg',
            'https://res.cloudinary.com/dlqyrgblr/image/upload/v1771770012/Clima_3_psgnid.jpg',
            'https://res.cloudinary.com/dlqyrgblr/image/upload/v1771770015/Clima_4_cb8rix.jpg',
        ],
        links: [
            { label: 'GitHub', url: 'https://github.com/Ridham2808/clima_predict', type: 'github' },
            { label: 'Live Site', url: 'https://climapredict-1.onrender.com/', type: 'live' },
            { label: 'Demo Video', url: 'https://drive.google.com/file/d/1VRkHVZKxHMTOQOBe_1hdQ7UGHv0UaobW/view', type: 'video' },
        ],
        badge: '🏆 Indradhanu 2026',
    },
    {
        id: 'smartreq', title: 'SmartReq AI', category: 'Hackathon',
        tagline: 'AI-Powered Requirement Gathering · Hackathon',
        description: 'An AI-powered platform that streamlines software requirement gathering — converts user inputs into structured, developer-ready requirement documents using generative AI.',
        features: ['AI requirement generation from prompts', 'Structured document output', 'Real-time collaboration', 'Requirement validation & review', 'Export to PDF/Markdown'],
        technologies: ['React.js', 'Node.js', 'Express.js', 'Generative AI', 'Vercel'],
        images: [
            'https://res.cloudinary.com/dlqyrgblr/image/upload/v1771769784/Screenshot_2026-02-22_194509_i7x7ac.png',
            'https://res.cloudinary.com/dlqyrgblr/image/upload/v1771769781/Screenshot_2026-02-22_194138_wbosfx.png',
            'https://res.cloudinary.com/dlqyrgblr/image/upload/v1771769779/Screenshot_2026-02-22_193935_a9prhh.png',
            'https://res.cloudinary.com/dlqyrgblr/image/upload/v1771769778/Screenshot_2026-02-22_194240_ti3ryf.png',
        ],
        links: [
            { label: 'GitHub', url: 'https://github.com/Ridham2808/SmartReq-AI', type: 'github' },
            { label: 'Live Site', url: 'https://smart-req-ai-wnj9.vercel.app/', type: 'live' },
        ],
        badge: '🤖 AI Hackathon',
    },
    {
        id: 'stockmaster', title: 'StockMaster', category: 'Hackathon',
        tagline: 'Inventory Management · Odoo × SPIT Hackathon',
        description: 'A comprehensive inventory management system built on Odoo, featuring real-time stock tracking, purchase order automation, vendor management, and intelligent stock alerts.',
        features: ['Real-time inventory tracking', 'Automated purchase order generation', 'Vendor & supplier management', 'Low stock alerts & notifications', 'Analytics and stock valuation reports'],
        technologies: ['Python', 'Odoo', 'PostgreSQL', 'XML', 'JavaScript'],
        images: [
            'https://res.cloudinary.com/dlqyrgblr/image/upload/v1771770419/Stock_master_1_axnqjt.png',
            'https://res.cloudinary.com/dlqyrgblr/image/upload/v1771770425/Stock_master_2_tjyg97.png',
            'https://res.cloudinary.com/dlqyrgblr/image/upload/v1771770421/Stock_master_3_dxsmus.png',
            'https://res.cloudinary.com/dlqyrgblr/image/upload/v1771770425/Stock_master_4_lzndlg.png',
        ],
        links: [
            { label: 'GitHub', url: 'https://github.com/Ridham2808/Odoo-Hackathon-StockMaster', type: 'github' },
            { label: 'Demo Video', url: 'https://drive.google.com/file/d/1JDQ73HCoOAbhQ5GqBf0eOgrfIYaQ0Sxo/view', type: 'video' },
        ],
        badge: '📦 Odoo × SPIT',
    },
    {
        id: 'synergysphere', title: 'SynergySphere', category: 'Hackathon',
        tagline: 'Team Collaboration Platform · Odoo Hackathon 2025',
        description: 'A unified team collaboration platform integrating task management, communication, HR tools, and project tracking into a single Odoo-powered workspace.',
        features: ['Unified task & project management', 'Team chat & announcements', 'HR leave & attendance tracking', 'Role-based access control', 'Real-time dashboard analytics'],
        technologies: ['Python', 'Odoo', 'PostgreSQL', 'JavaScript', 'XML'],
        images: [
            'https://res.cloudinary.com/dlqyrgblr/image/upload/v1771770758/SynergySphere_1_zduudm.png',
            'https://res.cloudinary.com/dlqyrgblr/image/upload/v1771770766/SynergySphere_2_x3k1x8.png',
            'https://res.cloudinary.com/dlqyrgblr/image/upload/v1771770766/SynergySphere_3_sasg9d.png',
            'https://res.cloudinary.com/dlqyrgblr/image/upload/v1771770768/SynergySphere_4_wat0na.png',
        ],
        links: [
            { label: 'GitHub', url: 'https://github.com/Ridham2808/Odoo-Hackathon2025-SynergySphere', type: 'github' },
            { label: 'Demo Video', url: 'https://youtu.be/pcbcsmPtEdE', type: 'video' },
        ],
        badge: '🔗 Odoo 2025',
    },
    {
        id: 'exman', title: 'ExMan', category: 'Hackathon',
        tagline: 'Expense Management System · Odoo Hackathon 2025',
        description: 'A smart expense management system built on Odoo that automates employee expense submissions, manager approvals, and finance team reimbursements with full audit trails.',
        features: ['Employee expense submission portal', 'Manager approval workflows', 'Finance reimbursement tracking', 'Multi-currency support', 'Automated audit trail & reporting'],
        technologies: ['Python', 'Odoo', 'PostgreSQL', 'JavaScript', 'XML'],
        images: [
            'https://res.cloudinary.com/dlqyrgblr/image/upload/v1771771133/ExMan_1_osu9ee.png',
            'https://res.cloudinary.com/dlqyrgblr/image/upload/v1771771125/ExMan_2_kpkg7r.png',
            'https://res.cloudinary.com/dlqyrgblr/image/upload/v1771771132/ExMan_3_fv53zp.png',
            'https://res.cloudinary.com/dlqyrgblr/image/upload/v1771771138/ExMan_4_mnezi3.png',
        ],
        links: [
            { label: 'GitHub', url: 'https://github.com/Ridham2808/Odoo_Hackathon-2025-expense-management-system', type: 'github' },
            { label: 'Demo Video', url: 'https://youtu.be/TZFhM4_FD_E', type: 'video' },
        ],
        badge: '💸 Odoo 2025',
    },
    {
        id: 'dayflow', title: 'Dayflow — Smart HR Platform', category: 'Hackathon',
        tagline: 'Smart HR Management · Hackathon Project',
        description: 'A next-generation Smart HR platform with employee lifecycle management, leave tracking, payroll, attendance, performance reviews, and an admin analytics dashboard.',
        features: ['Employee onboarding & lifecycle management', 'Leave & attendance tracking', 'Payroll automation', 'Performance review system', 'Admin analytics dashboard', 'Role-based access (Admin/Employee)'],
        technologies: ['Next.js', 'Node.js', 'Prisma', 'PostgreSQL', 'JWT', 'Tailwind CSS'],
        images: [
            'https://res.cloudinary.com/dlqyrgblr/image/upload/v1771773635/Dayflow_1_nmmlnq.png',
            'https://res.cloudinary.com/dlqyrgblr/image/upload/v1771773637/Dayflow_2_njr0av.png',
            'https://res.cloudinary.com/dlqyrgblr/image/upload/v1771773663/Dayflow_3_ikr9fe.png',
            'https://res.cloudinary.com/dlqyrgblr/image/upload/v1771773663/Dayflow_4_eebd0n.png',
        ],
        links: [
            { label: 'GitHub', url: 'https://github.com/Ridham2808/dayflow-smart-hr-platform', type: 'github' },
            { label: 'Demo Video', url: 'https://drive.google.com/file/d/1tHuRudFlK0baQwdN4U780ZovGTmARXsK/view', type: 'video' },
        ],
        badge: '👥 Smart HR',
    },

    // ─── Open Source ──────────────────────────────────────────────
    {
        id: 'task-bridge', title: 'Task Bridge', category: 'Open Source',
        tagline: 'Interactive Virtual Whiteboard · OSS Contribution',
        description: 'Implemented an interactive virtual whiteboard module in the Task Bridge open-source project using React and Fabric.js — enabling freehand drawing, shapes, text tools, color selection, and persistent state management.',
        features: ['Freehand drawing with Fabric.js', 'Shape & text tool support', 'Color, brush size, opacity controls', 'Draggable canvas objects', 'Persistent state across sessions'],
        technologies: ['React.js', 'Fabric.js', 'Canvas API', 'JavaScript', 'CSS3'],
        images: ['https://res.cloudinary.com/dlqyrgblr/image/upload/v1771778316/TaskBridge_amhdrp.png'],
        links: [
            { label: 'My Fork', url: 'https://github.com/Ridham2808/task_bridge', type: 'github' },
            { label: 'Merged PR', url: 'https://github.com/codinggita/task_bridge/pull/35', type: 'pr' },
            { label: 'Issue', url: 'https://github.com/codinggita/task_bridge/issues/31', type: 'issue' },
        ],
        badge: '🔓 Open Source',
    },
    {
        id: 'tattoo-studio', title: 'Tattoo Studio Website', category: 'Open Source',
        tagline: 'Reviews & Testimonials System · OSS Contribution',
        description: 'Developed a complete client reviews and testimonials system with star ratings, image uploads, and admin moderation, improving platform trust, user engagement, and credibility.',
        features: ['Star rating system', 'Client review submission with image uploads', 'Admin moderation panel', 'Verified testimonials display', 'Improved user engagement metrics'],
        technologies: ['React.js', 'Node.js', 'MongoDB', 'Express.js', 'Multer'],
        images: ['https://res.cloudinary.com/dlqyrgblr/image/upload/v1771778530/Tattoo_jvr8tr.png'],
        links: [
            { label: 'My Fork', url: 'https://github.com/Ridham2808/tattoos_website', type: 'github' },
            { label: 'Merged PR', url: 'https://github.com/codinggita/tattoos_website/pull/22', type: 'pr' },
            { label: 'Issue', url: 'https://github.com/codinggita/tattoos_website/issues/17', type: 'issue' },
        ],
        badge: '🔓 Open Source',
    },
    {
        id: 'animeverse', title: 'AnimeVerse', category: 'Open Source',
        tagline: 'JWT Auth & RBAC System · OSS Contribution',
        description: 'Implemented a secure JWT-based authentication system with role-based access control (Admin/User), forgot password functionality, and login email notifications using MongoDB for session management.',
        features: ['JWT-based authentication', 'Role-based access control (Admin/User)', 'Forgot password with email reset', 'Login email notifications', 'MongoDB-powered session management'],
        technologies: ['React.js', 'Node.js', 'MongoDB', 'Express.js', 'JWT', 'Nodemailer'],
        images: ['https://res.cloudinary.com/dlqyrgblr/image/upload/v1771778323/Anime_qpihxa.png'],
        links: [
            { label: 'My Fork', url: 'https://github.com/Ridham2808/anime_world', type: 'github' },
            { label: 'Merged PR', url: 'https://github.com/codinggita/anime_world/pull/24', type: 'pr' },
            { label: 'Issue', url: 'https://github.com/codinggita/anime_world/issues/20', type: 'issue' },
        ],
        badge: '🔓 Open Source',
    },

    // ─── Figma / UI Design ────────────────────────────────────────
    {
        id: 'ironcore-figma', title: 'Ironcore Gym (Figma)', category: 'Figma / UI Design',
        tagline: 'Full Design System',
        description: 'Complete UI/UX design for the Ironcore Gym platform — membership plans, BMI tools, fitness blogs, and a full design system.',
        features: ['Full design system & components', 'Membership & trainer UI', 'Mobile-first approach', 'Interactive prototyping'],
        technologies: ['Figma', 'Prototyping', 'UI/UX', 'Design System'],
        images: ['https://res.cloudinary.com/dlqyrgblr/image/upload/v1739888624/rkkaw5ixxwkhg8tn4ckl.png'],
        links: [{ label: 'View in Figma', url: 'https://www.figma.com/design/xx6t46xMZOAVmXsBXRbliP/Ironcore-Gym?node-id=0-1', type: 'figma' }],
    },
    {
        id: 'documorph-figma', title: 'DocuMorph', category: 'Figma / UI Design',
        tagline: 'Document Platform Design',
        description: 'Document scanning & comparison platform design with similarity highlighting, bulk processing, and a clean minimal UI.',
        features: ['Document comparison UI', 'Similarity highlighting', 'Bulk processing workflow', 'Clean & minimal design'],
        technologies: ['Figma', 'Prototyping', 'UI/UX'],
        images: ['https://res.cloudinary.com/dlqyrgblr/image/upload/v1741255758/Screenshot_2025-03-06_153758_tcuw5i.png'],
        links: [{ label: 'View in Figma', url: 'https://www.figma.com/design/dDZOorjYWbhPg7yKGxtpic/DocuMorph?node-id=0-1', type: 'figma' }],
    },
    {
        id: 'codinggita-figma', title: 'CodingGita', category: 'Figma / UI Design',
        tagline: 'Animated Web Design',
        description: 'Fully animated Figma design — Home, Bootcamp, Contact, About, with scrollable overlays and hover effects.',
        features: ['Multi-page design system', 'Animated scroll overlays', 'Bootcamp section UI', 'Interactive hover states'],
        technologies: ['Figma', 'Wireframing', 'Design System', 'Animation'],
        images: ['https://res.cloudinary.com/dlqyrgblr/image/upload/v1739888440/flnic7pnzmg1ofiizuml.png'],
        links: [{ label: 'View in Figma', url: 'https://www.figma.com/design/RdZHGbiXDFn75Mc8cTC40K/CodingGita?node-id=0-1', type: 'figma' }],
    },
    {
        id: 'instagram-figma', title: 'Instagram Clone', category: 'Figma / UI Design',
        tagline: 'Social Media UI Clone',
        description: 'Instagram UI clone — story highlights, dynamic feed, user profiles, modern social media design system.',
        features: ['Stories & highlights UI', 'Dynamic feed layout', 'User profile screens', 'Modern social design'],
        technologies: ['Figma', 'UI Design', 'Prototyping'],
        images: ['https://res.cloudinary.com/dlqyrgblr/image/upload/v1739888593/swhcqzizianbpa5xvu80.png'],
        links: [{ label: 'View in Figma', url: 'https://www.figma.com/design/hyb8A5mWFKgQToD7YWeGry/Instagram?node-id=0-1', type: 'figma' }],
    },
    {
        id: 'amazon-figma', title: 'Amazon Clone', category: 'Figma / UI Design',
        tagline: 'E-Commerce UI Design',
        description: 'Amazon shopping experience design — product listings, cart, user authentication. Optimized for intuitive e-commerce navigation.',
        features: ['Product listing UI', 'Shopping cart flow', 'Auth screens', 'E-commerce navigation pattern'],
        technologies: ['Figma', 'Wireframing', 'Design System'],
        images: ['https://res.cloudinary.com/dlqyrgblr/image/upload/v1739888392/amnmqdoo1383wgsebyem.png'],
        links: [{ label: 'View in Figma', url: 'https://www.figma.com/design/FROVsJRuptn0lvRybHFMV0/amazon?node-id=0-1', type: 'figma' }],
    },
    {
        id: 'netflix-figma', title: 'Netflix Clone', category: 'Figma / UI Design',
        tagline: 'Streaming Platform UI',
        description: 'Netflix UI design — homepage, categories, interactive previews, watchlist. Modern streaming experience.',
        features: ['Streaming homepage layout', 'Category & genre sections', 'Video preview UI', 'Watchlist screens'],
        technologies: ['Figma', 'Prototyping', 'UI/UX'],
        images: ['https://res.cloudinary.com/dlqyrgblr/image/upload/v1739888670/fbzdibcpzdnvxm3t5xso.png'],
        links: [{ label: 'View in Figma', url: 'https://www.figma.com/design/MDRkCvsN7P0eg1E7hxxuF3/Netflix?node-id=0-1', type: 'figma' }],
    },

    // ─── HTML & CSS ────────────────────────────────────────────────
    {
        id: 'godesi', title: 'Godesi Website', category: 'HTML & CSS',
        tagline: 'Traditional E-Commerce Clone',
        description: 'A Godesi website clone using HTML/CSS with auto-scrolling sidebar, hover effects, and traditional Indian design aesthetic.',
        features: ['Auto-scrolling sidebar', 'Product hover effects', 'Traditional design aesthetic', 'Responsive layout'],
        technologies: ['HTML5', 'CSS3', 'Responsive Design'],
        images: ['https://res.cloudinary.com/dlqyrgblr/image/upload/v1739894688/vsly8jnuoryzbxr0b21g.png'],
        links: [{ label: 'GitHub', url: 'https://github.com/Ridham2808/godesi', type: 'github' }, { label: 'Live Site', url: 'https://godesi.netlify.app/', type: 'live' }],
    },
    {
        id: 'hourly-hotels', title: 'Hourly Hotels', category: 'HTML & CSS',
        tagline: 'Hotel Listing UI',
        description: 'A static hotel listing website with clean layout, hotel cards, and fully responsive design.',
        features: ['Hotel card layout', 'Responsive grid', 'Clean minimal UI', 'CSS hover transitions'],
        technologies: ['HTML5', 'CSS3', 'Flexbox'],
        images: ['https://res.cloudinary.com/dlqyrgblr/image/upload/v1739894704/zoy2wyoq8psfznqpeb0q.png'],
        links: [{ label: 'GitHub', url: 'https://github.com/Ridham2808/hourly-hotels', type: 'github' }, { label: 'Live Site', url: 'https://hourly-hotels.netlify.app', type: 'live' }],
    },
    {
        id: 'chess', title: 'Chess Game UI', category: 'HTML & CSS',
        tagline: 'Classic Board Game UI',
        description: 'A classic Chess board UI with accurate piece layout built purely in HTML/CSS.',
        features: ['Accurate chess board layout', 'Piece positioning', 'Pure CSS styling', 'No JavaScript required'],
        technologies: ['HTML5', 'CSS3', 'Grid Layout'],
        images: ['https://res.cloudinary.com/dlqyrgblr/image/upload/v1739894652/a1sa17rdasr77a5ndo7j.png'],
        links: [{ label: 'GitHub', url: 'https://github.com/Ridham2808/Clone/tree/main/Chess', type: 'github' }, { label: 'Live Site', url: 'https://ridhamchess.netlify.app/', type: 'live' }],
    },
    {
        id: 'calculator', title: 'Calculator', category: 'HTML & CSS',
        tagline: 'Functional Calculator',
        description: 'A functional calculator with arithmetic operations, clean UI, and keyboard support.',
        features: ['Arithmetic operations', 'Keyboard input support', 'Clean modern UI', 'Error handling'],
        technologies: ['HTML5', 'CSS3', 'JavaScript'],
        images: ['https://res.cloudinary.com/dlqyrgblr/image/upload/v1739894636/unwpoek85uyswuhh9axa.png'],
        links: [{ label: 'GitHub', url: 'https://github.com/Ridham2808/Clone/tree/main/calculator', type: 'github' }, { label: 'Live Site', url: 'https://ridhamcalc.netlify.app/', type: 'live' }],
    },
    {
        id: 'ludo', title: 'Ludo Game UI', category: 'HTML & CSS',
        tagline: 'Colorful Board Game UI',
        description: 'A colorful Ludo board UI with player tokens and visually appealing static design.',
        features: ['Accurate Ludo board layout', 'Color-coded player tokens', 'Pure CSS implementation', 'Responsive design'],
        technologies: ['HTML5', 'CSS3', 'Flexbox'],
        images: ['https://res.cloudinary.com/dlqyrgblr/image/upload/v1739894715/j1k1zhkamjzu9itbkupi.png'],
        links: [{ label: 'GitHub', url: 'https://github.com/Ridham2808/Clone/tree/main/ludo', type: 'github' }, { label: 'Live Site', url: 'https://ridhamludo.netlify.app/', type: 'live' }],
    },
];

export const TABS = [
    { id: 'All', label: 'All' },
    { id: 'Full Stack', label: 'Full Stack' },
    { id: 'Hackathon', label: 'Hackathon Team Project' },
    { id: 'Open Source', label: 'Open Source' },
    { id: 'Figma / UI Design', label: 'Figma / UI' },
    { id: 'HTML & CSS', label: 'HTML & CSS' },
];

export const LINK_ICONS = {
    github: '{ }',
    live: '↗',
    video: '▶',
    docs: '📄',
    pr: '⤷',
    issue: '◎',
    figma: '◈',
};
